Repository narvis2/Reservation-App, pull requests merged in 2023-08, with the labels that each got.

#23 공지사항 탭 추가
  lib/presentation/config/router/app_router.dart
  lib/presentation/config/router/app_router.gr.dart
  lib/presentation/utils/constants.dart
  lib/presentation/views/main/tabs/home/home_tab_screen.dart
  lib/presentation/views/main/tabs/home/tabs/notice/component/gallery_item_thumbnail.dart
  lib/presentation/views/main/tabs/home/tabs/notice/content_notice_tab_screen.dart
  lib/presentation/views/notice/notice_detail_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: add

#22 🦋 Firebase Cloud Messaging + Local Notification 🦋
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/thepan/woohwedahm/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  ios/firebase_app_id_file.json
  lib/data/model/reservation/reservation_create_request.dart
  lib/data/model/reservation/reservation_create_request.g.dart
  lib/data/repository/fcm/fcm_repository.dart
  lib/data/repository/reservation/reservation_repository_impl.dart
  lib/data/utils/Endpoints.dart
  lib/di/dependency_inection_graph.dart
  lib/di/prefs/shared_pref_module.dart
  lib/domain/model/fcm/enum/notification_type.dart
  lib/domain/model/fcm/fcm_notification_data_model.dart
  lib/domain/model/fcm/fcm_notification_model.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/presentation/views/common/network_error_widget.dart
  lib/presentation/views/fcm/bloc/fcm_notification_bloc.dart
  lib/presentation/views/fcm/bloc/fcm_notification_event.dart
  lib/presentation/views/fcm/bloc/fcm_notification_state.dart
  lib/presentation/views/main/main_screen.dart
  lib/presentation/views/main/tabs/home/components/top_area_component.dart
  lib/presentation/views/network/bloc/network_bloc.dart
  lib/presentation/views/network/bloc/network_bloc.freezed.dart
  lib/presentation/views/reservation/view/reservation_fourth_process_view.dart
  lib/presentation/views/splash/splash_screen.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: add

#26 🦋 TabLayout Scroll Animation 수정 🦋
  lib/presentation/views/main/tabs/home/pager/home_pager_screen.dart
Labels: add

#27 🦋 로그인과 로그아웃 기능에 필요한 API 추가 🦋
  lib/data/datasources/remote/member/member_api_service.dart
  lib/data/datasources/remote/member/member_api_service.g.dart
  lib/data/datasources/remote/sign/sign_api_service.dart
  lib/data/datasources/remote/sign/sign_api_service.g.dart
  lib/data/mapper/object_mapper.dart
  lib/data/model/member/member_info_response.dart
  lib/data/model/member/member_info_response.g.dart
  lib/data/model/member/member_update_fcm_token_request.dart
  lib/data/model/member/member_update_fcm_token_request.g.dart
  lib/data/model/role/role_type.dart
  lib/data/model/sign/sign_in_request.dart
  lib/data/model/sign/sign_in_request.g.dart
  lib/data/model/sign/sign_in_response.dart
  lib/data/model/sign/sign_in_response.g.dart
  lib/data/model/sign/sign_out_request.dart
  lib/data/model/sign/sign_out_request.g.dart
  lib/data/repository/member/member_repository_impl.dart
  lib/data/repository/sign/sign_repository_impl.dart
  lib/di/dependency_inection_graph.dart
  lib/domain/model/sign/sign_in_request_model.dart
  lib/domain/repository/member/member_repository.dart
  lib/domain/repository/sign/sign_repository.dart
  lib/domain/usecase/member/get_my_user_info_use_case.dart
  lib/domain/usecase/member/request_update_fcm_token_use_case.dart
  lib/domain/usecase/sign/request_sign_in_use_case.dart
  lib/domain/usecase/sign/request_sign_out_use_case.dart
Labels: add

#28 🦋 /sign/signOut API RequestBody 수정 🦋
  lib/data/datasources/remote/sign/sign_api_service.dart
  lib/data/datasources/remote/sign/sign_api_service.g.dart
  lib/data/model/sign/sign_out_request.dart
  lib/data/model/sign/sign_out_request.g.dart
  lib/data/repository/sign/sign_repository_impl.dart
Labels: modify

#29 🧹 코드 정리 🧹
  lib/di/dependency_injection_graph.dart
  lib/di/network/network_module.dart
  lib/main.dart
  lib/presentation/views/main/bloc/main_bloc.dart
  lib/presentation/views/main/bloc/main_event.dart
  lib/presentation/views/main/bloc/main_state.dart
  lib/presentation/views/main/main_screen.dart
  lib/presentation/views/main/tabs/home/bloc/home_tab_bloc.dart
  lib/presentation/views/main/tabs/home/bloc/home_tab_event.dart
  lib/presentation/views/main/tabs/home/bloc/home_tab_state.dart
  lib/presentation/views/main/tabs/home/components/top_area_component.dart
  lib/presentation/views/main/tabs/home/home_tab_screen.dart
  lib/presentation/views/main/tabs/home/pager/home_pager_screen.dart
  lib/presentation/views/main/tabs/home/tabs/home/content_home_tab_screen.dart
  lib/presentation/views/main/tabs/home/tabs/location/content_location_tab_screen.dart
  lib/presentation/views/reservation/reservation_screen.dart
  lib/presentation/views/splash/splash_screen.dart
Labels: clean-up

#30 🦋 Clean Architecture 구조 수정 🦋
  lib/data/api/banner/banner_api_service.dart
  lib/data/api/banner/banner_api_service.g.dart
  lib/data/api/member/member_api_service.dart
  lib/data/api/member/member_api_service.g.dart
  lib/data/api/notice/notice_api_service.dart
  lib/data/api/notice/notice_api_service.g.dart
  lib/data/api/reservation/reservation_api_service.dart
  lib/data/api/reservation/reservation_api_service.g.dart
  lib/data/api/sign/sign_api_service.dart
  lib/data/api/sign/sign_api_service.g.dart
  lib/data/datasource/impl/remote_data_source_impl.dart
  lib/data/datasource/remote_data_source.dart
  lib/data/repository/banner/banner_repository_impl.dart
  lib/data/repository/member/member_repository_impl.dart
  lib/data/repository/notice/notice_repository_impl.dart
  lib/data/repository/reservation/reservation_repository_impl.dart
  lib/data/repository/sign/sign_repository_impl.dart
  lib/di/dependency_injection_graph.dart
Labels: add, modify

#31 🦋 로그인/로그아웃 기능 구현 🦋
  assets/images/master_white.png
  ios/Podfile.lock
  lib/data/mapper/object_mapper.dart
  lib/data/model/member/member_info_response.dart
  lib/data/model/member/member_info_response.g.dart
  lib/data/model/role/role_type.dart
  lib/data/repository/fcm/fcm_repository.dart
  lib/data/repository/member/member_repository_impl.dart
  lib/data/repository/sign/sign_repository_impl.dart
  lib/di/dependency_injection_graph.dart
  lib/di/prefs/shared_pref_module.dart
  lib/main.dart
  lib/presentation/utils/color_constants.dart
  lib/presentation/utils/dialog_utils.dart
  lib/presentation/utils/obj_extensions.dart
  lib/presentation/utils/text_utils.dart
  lib/presentation/views/app/bloc/app_info_bloc.dart
  lib/presentation/views/app/bloc/app_info_bloc.freezed.dart
  lib/presentation/views/app/bloc/app_info_event.dart
  lib/presentation/views/app/bloc/app_info_state.dart
  lib/presentation/views/main/main_screen.dart
  lib/presentation/views/main/tabs/setting/setting_tab_screen.dart
  lib/presentation/views/main/tabs/setting/widget/app_setting_content_widget.dart
  lib/presentation/views/main/tabs/setting/widget/app_version_widget.dart
  lib/presentation/views/main/tabs/setting/widget/profile_widget.dart
  lib/presentation/views/main/tabs/setting/widget/setting_category_title_widget.dart
  lib/presentation/views/main/tabs/setting/widget/sign_out_widget.dart
  lib/presentation/views/sign/bloc/sign_bloc.dart
  lib/presentation/views/sign/bloc/sign_bloc.freezed.dart
  lib/presentation/views/sign/bloc/sign_event.dart
  lib/presentation/views/sign/bloc/sign_state.dart
  lib/presentation/views/sign/enum/InputType.dart
  lib/presentation/views/sign/signin_signup_screen.dart
  lib/presentation/views/sign/widget/signin_signup_button_widget.dart
  lib/presentation/views/sign/widget/signin_signup_input_widget.dart
  lib/presentation/views/sign/widget/signin_signup_title_area_widget.dart
  lib/presentation/views/sign/widget/signin_signup_toggle_button_widget.dart
  lib/presentation/views/splash/splash_screen.dart
  lib/presentation/views/user/bloc/user_info_bloc.dart
  lib/presentation/views/user/bloc/user_info_bloc.freezed.dart
  lib/presentation/views/user/bloc/user_info_event.dart
  lib/presentation/views/user/bloc/user_info_state.dart
  pubspec.lock
  pubspec.yaml
Labels: add

#32 🦋 Member Info Response 수정 🦋
  lib/data/mapper/object_mapper.dart
  lib/data/model/member/member_info_response.dart
  lib/data/model/member/member_info_response.g.dart
  lib/data/repository/member/member_repository_impl.dart
  lib/domain/model/member/member_model.dart
  lib/domain/model/member/member_model.g.dart
  lib/presentation/views/main/main_screen.dart
  lib/presentation/views/main/tabs/setting/setting_tab_screen.dart
  lib/presentation/views/main/tabs/setting/widget/profile_widget.dart
Labels: modify

#33 🦋 id 저장 비활성화 시 저장되어있던 id 삭제하는 로직 추가 🦋
  lib/presentation/views/sign/bloc/sign_bloc.dart
Labels: modify

#34 🦋 BaseUrl 변경 🦋
  lib/data/utils/Endpoints.dart
Labels: modify

#35 🦋 BottomNavigation 👉 Search 영역 내부 View 생성 🦋
  lib/presentation/utils/constants.dart
  lib/presentation/views/main/main_screen.dart
  lib/presentation/views/main/tabs/profile/search_tab_screen.dart
  lib/presentation/views/main/tabs/search/calendar/reservation_calendar_tab_screen.dart
  lib/presentation/views/main/tabs/search/chart/reservation_chart_tab_screen.dart
  lib/presentation/views/main/tabs/search/check/reservation_check_tab_screen.dart
  lib/presentation/views/main/tabs/search/search_tab_screen.dart
Labels: add

#36 🦋 관리자 > 비승인된 예약 목록을 가져오는 API 추가 🦋
  lib/data/api/reservation/reservation_api_service.dart
  lib/data/api/reservation/reservation_api_service.g.dart
  lib/data/datasource/impl/remote_data_source_impl.dart
  lib/data/datasource/remote_data_source.dart
  lib/data/mapper/object_mapper.dart
  lib/data/model/reservation/reservation_non_auth_response.dart
  lib/data/model/reservation/reservation_non_auth_response.g.dart
  lib/data/repository/reservation/reservation_repository_impl.dart
  lib/di/dependency_injection_graph.dart
  lib/domain/model/reservation/reservation_non_auth_model.dart
  lib/domain/repository/reservation/reservation_repository.dart
  lib/domain/usecase/reservation/get_reservation_non_auth_list_use_case.dart
  lib/presentation/views/main/tabs/search/chart/bloc/reservation_check_bloc.dart
  lib/presentation/views/main/tabs/search/chart/bloc/reservation_check_bloc.freezed.dart
  lib/presentation/views/main/tabs/search/chart/bloc/reservation_check_event.dart
  lib/presentation/views/main/tabs/search/chart/bloc/reservation_check_state.dart
Labels: add

#37 🦋 예약 목록 Filtering 및 Pagination 구현 🦋
  assets/lottie/empty_animation.json
  lib/data/api/reservation/reservation_api_service.dart
  lib/data/api/reservation/reservation_api_service.g.dart
  lib/data/datasource/impl/remote_data_source_impl.dart
  lib/data/datasource/remote_data_source.dart
  lib/data/mapper/object_mapper.dart
  lib/data/model/reservation/reservation_approval_check_request.dart
  lib/data/model/reservation/reservation_approval_check_request.g.dart
  lib/data/repository/reservation/reservation_repository_impl.dart
  lib/di/dependency_injection_graph.dart
  lib/domain/model/common/bottom_sheet_model.dart
  lib/domain/model/reservation/page/reservation_filter_model.dart
  lib/domain/model/reservation/page/reservation_filter_model.freezed.dart
  lib/domain/model/reservation/request/reservation_approval_check_request_model.dart
  lib/domain/repository/reservation/reservation_repository.dart
  lib/domain/usecase/reservation/request_approval_check_reservation_use_case.dart
  lib/presentation/config/router/app_router.dart
  lib/presentation/config/router/app_router.gr.dart
  lib/presentation/utils/constants.dart
  lib/presentation/utils/date_time_utils.dart
  lib/presentation/utils/dialog_utils.dart
  lib/presentation/utils/list_extensions.dart
  lib/presentation/utils/snack_bar_utils.dart
  lib/presentation/views/common/empty_widget.dart
  lib/presentation/views/main/tabs/search/check/bloc/reservation_check_bloc.dart
  lib/presentation/views/main/tabs/search/check/bloc/reservation_check_bloc.freezed.dart
  lib/presentation/views/main/tabs/search/check/bloc/reservation_check_event.dart
  lib/presentation/views/main/tabs/search/check/bloc/reservation_check_state.dart
  lib/presentation/views/main/tabs/search/check/details/reservation_check_tab_details_screen.dart
  lib/presentation/views/main/tabs/search/check/model/menu_item_model.dart
  lib/presentation/views/main/tabs/search/check/reservation_check_tab_screen.dart
  lib/presentation/views/main/tabs/search/check/utils/check_utils.dart
  lib/presentation/views/main/tabs/search/check/widget/adapter/reservation_filter_list_adapter.dart
  lib/presentation/views/main/tabs/search/check/widget/check_top_area_widget.dart
  lib/presentation/views/main/tabs/search/check/widget/expand/expand_filter_widget.dart
  lib/presentation/views/main/tabs/search/check/widget/expand/expand_menu_widget.dart
  lib/presentation/views/main/tabs/search/search_tab_screen.dart
  lib/presentation/views/reservation/widget/reservation_select_date_widget.dart
  lib/presentation/views/splash/splash_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: add

#38 🦋 예약 정보 상세 화면 구현 🦋
  lib/data/api/reservation/reservation_api_service.dart
  lib/data/api/reservation/reservation_api_service.g.dart
  lib/data/datasource/impl/remote_data_source_impl.dart
  lib/data/datasource/remote_data_source.dart
  lib/data/mapper/object_mapper.dart
  lib/data/model/reservation/reservation_detail_response.dart
  lib/data/model/reservation/reservation_detail_response.freezed.dart
  lib/data/model/reservation/reservation_detail_response.g.dart
  lib/data/repository/reservation/reservation_repository_impl.dart
  lib/di/dependency_injection_graph.dart
  lib/domain/model/reservation/reservation_detail_model.dart
  lib/domain/repository/reservation/reservation_repository.dart
  lib/domain/usecase/reservation/request_reservation_detail_by_user_use_case.dart
  lib/domain/usecase/reservation/request_reservation_detail_use_case.dart
  lib/presentation/config/router/app_router.gr.dart
  lib/presentation/utils/date_time_utils.dart
  lib/presentation/utils/dialog_utils.dart
  lib/presentation/views/main/tabs/home/tabs/location/content_location_tab_screen.dart
  lib/presentation/views/main/tabs/search/check/details/bloc/reservation_check_detail_bloc.dart
  lib/presentation/views/main/tabs/search/check/details/bloc/reservation_check_detail_bloc.freezed.dart
  lib/presentation/views/main/tabs/search/check/details/bloc/reservation_check_detail_event.dart
  lib/presentation/views/main/tabs/search/check/details/bloc/reservation_check_detail_state.dart
  lib/presentation/views/main/tabs/search/check/details/reservation_check_tab_details_screen.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_detail_botton.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_detail_content_button_widget.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_detail_content_widget.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_detail_info_widget.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_detail_seat_info_widget.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_detail_terms_agree_widget.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_dtails_view.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_detail_user_info_widget.dart
  lib/presentation/views/main/tabs/search/check/reservation_check_tab_screen.dart
  lib/presentation/views/main/tabs/search/check/utils/check_utils.dart
Labels: add

#39 🦋 예약 정보 확인 기능 추가 🦋
  lib/presentation/utils/dialog_utils.dart
  lib/presentation/views/main/tabs/home/home_tab_screen.dart
  lib/presentation/views/main/tabs/search/check/details/bloc/reservation_check_detail_bloc.dart
  lib/presentation/views/main/tabs/search/check/details/widget/reservation_check_dtails_view.dart
  lib/presentation/views/main/tabs/search/check/dialog/reservation_check_dialog_screen.dart
  lib/presentation/views/main/tabs/search/check/dialog/widget/check_dialog_confirm_button_widget.dart
  lib/presentation/views/main/tabs/search/check/dialog/widget/check_dialog_input_widget.dart
Labels: add

#40 🦋 Flutter Version Update 3.13.1 🦋
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/presentation/config/router/app_router.gr.dart
  pubspec.lock
  pubspec.yaml
Labels: flutter-verion-update
